import {
  FOOD_ACTION_CHIPS,
  MICRO_TRIP_ACTION_CHIPS,
  MOCK_TIMESTAMP,
  RECOVERY_ACTION_CHIPS,
  SPORTS_ACTION_CHIPS,
} from "./constants";
import type { FeedItem } from "./types";

export const mockFeedItems: FeedItem[] = [
  {
    id: "video-001",
    type: "video",
    createdAt: MOCK_TIMESTAMP,
    author: {
      id: "creator-city-walk",
      handle: "@citypulse",
      displayName: "City Pulse",
      avatarColor: "#38bdf8",
    },
    caption: "Three corners near the station that look better after rain.",
    soundtrack: "lofi evening loop",
    posterColor: "#164e63",
    tags: ["citywalk", "rain", "local"],
    stats: { likes: "18.2k", comments: "642", shares: "1.9k" },
  },
  {
    id: "card-food-001",
    type: "food",
    createdAt: MOCK_TIMESTAMP,
    eyebrow: "Dinner decision",
    headline: "Go for tomato beef rice before the rush",
    personalReason:
      "You are hungry, nearby, and have a 30 minute window before delivery times spike.",
    confidenceLabel: "High match",
    selectedIntent: "default",
    userContext: {
      location: "Xujiahui",
      localTime: "18:20",
      weather: "Light rain",
      mood: "hungry",
      budgetCny: 45,
      companions: "alone",
      dietaryPreference: "balanced",
    },
    actionChips: [...FOOD_ACTION_CHIPS],
    mealWindow: "dinner",
    core: {
      recommendation: {
        name: "Tomato beef rice bowl",
        cuisine: "Chinese fast casual",
        priceCny: 36,
        distanceMinutes: 8,
        deliveryAvailable: true,
        caloriesLabel: "Medium",
        reason: "Warm, filling, quick, and not too heavy for a rainy evening.",
      },
      backup: {
        name: "Mushroom chicken noodle soup",
        cuisine: "Noodles",
        priceCny: 32,
        distanceMinutes: 10,
        deliveryAvailable: true,
        caloriesLabel: "Medium",
        reason: "A softer backup if you want something soupy.",
      },
      avoid: "Skip hot pot tonight; queue time is the main risk.",
      orderTip: "Ask for extra tomato broth and keep rice separate.",
    },
  },
  {
    id: "video-002",
    type: "video",
    createdAt: MOCK_TIMESTAMP,
    author: {
      id: "creator-food-map",
      handle: "@noqueuebites",
      displayName: "No Queue Bites",
      avatarColor: "#fb7185",
    },
    caption: "A tiny counter meal under 40 RMB near office towers.",
    soundtrack: "street food snap",
    posterColor: "#7f1d1d",
    tags: ["food", "budget", "workday"],
    stats: { likes: "25.7k", comments: "831", shares: "3.1k" },
  },
  {
    id: "card-trip-001",
    type: "micro-trip",
    createdAt: MOCK_TIMESTAMP,
    eyebrow: "Two-hour escape",
    headline: "Take a quiet bookshop and riverside loop",
    personalReason:
      "The rain is easing, and you have just enough time for a low-pressure reset nearby.",
    confidenceLabel: "Easy plan",
    selectedIntent: "default",
    userContext: {
      location: "Xujiahui",
      localTime: "15:10",
      weather: "Cloudy after rain",
      mood: "restless",
      budgetCny: 80,
      companions: "friend",
      mobilityPreference: "normal",
    },
    actionChips: [...MICRO_TRIP_ACTION_CHIPS],
    tripWindow: "15:30-17:30",
    core: {
      theme: "Slow city reset",
      totalCostCny: 58,
      walkingMinutes: 24,
      route: [
        {
          title: "Independent bookshop",
          durationMinutes: 35,
          note: "Start indoors while the pavement dries.",
        },
        {
          title: "Riverside coffee window",
          durationMinutes: 30,
          note: "Grab a small latte and sit facing the water.",
        },
        {
          title: "Plane-tree side street",
          durationMinutes: 25,
          note: "Short walk with enough light for a final clip.",
        },
      ],
      bestMoment: "Film the river reflection just before 17:00.",
    },
  },
  {
    id: "video-003",
    type: "video",
    createdAt: MOCK_TIMESTAMP,
    author: {
      id: "creator-sports",
      handle: "@matchtempo",
      displayName: "Match Tempo",
      avatarColor: "#22c55e",
    },
    caption: "Warmups tell you more than the odds board tonight.",
    soundtrack: "stadium build",
    posterColor: "#14532d",
    tags: ["football", "prematch", "watch"],
    stats: { likes: "41.4k", comments: "2.4k", shares: "5.6k" },
  },
  {
    id: "card-sports-001",
    type: "sports",
    createdAt: MOCK_TIMESTAMP,
    eyebrow: "Pre-match read",
    headline: "Expect a tight first half before the home press rises",
    personalReason:
      "You usually watch highlights, so this keeps the angle simple without betting language.",
    confidenceLabel: "Balanced read",
    selectedIntent: "default",
    userContext: {
      location: "Shanghai",
      localTime: "19:45",
      weather: "Indoor viewing",
      mood: "focused",
      companions: "team",
    },
    actionChips: [...SPORTS_ACTION_CHIPS],
    match: {
      league: "Continental Cup",
      startsAt: "20:30",
      home: { name: "Harbor City", form: "W-D-W-L-W" },
      away: { name: "North United", form: "D-W-D-W-L" },
    },
    core: {
      angle: "Harbor City can control territory, but North United are dangerous after turnovers.",
      lean: "watch",
      oneLine: "Watch the first 20 minutes: pressure volume matters more than possession.",
      signals: [
        { label: "Home edge", value: "Wide pressing lanes" },
        { label: "Away threat", value: "Fast left-side counters" },
        { label: "Tempo", value: "Cautious start, quicker second half" },
      ],
    },
  },
  {
    id: "card-recovery-001",
    type: "recovery",
    createdAt: MOCK_TIMESTAMP,
    eyebrow: "Soft reset",
    headline: "Do a three-step nervous-system downshift",
    personalReason:
      "You have been scrolling at night, and your context suggests tired rather than bored.",
    confidenceLabel: "Gentle",
    selectedIntent: "default",
    userContext: {
      location: "Home",
      localTime: "22:40",
      weather: "Quiet room",
      mood: "tired",
      companions: "alone",
    },
    actionChips: [...RECOVERY_ACTION_CHIPS],
    recoveryWindow: "10 minutes",
    core: {
      tone: "calm",
      steps: [
        {
          title: "Lower the light",
          durationMinutes: 1,
          instruction: "Dim the room and put the phone face down.",
        },
        {
          title: "Unclench",
          durationMinutes: 3,
          instruction: "Relax jaw, shoulders, hands, and belly in that order.",
        },
        {
          title: "Slow exhale",
          durationMinutes: 6,
          instruction: "Breathe in normally, then make each exhale slightly longer.",
        },
      ],
      closingCue: "Stop when your shoulders feel two centimeters lower.",
    },
  },
];

export const mockAiCards = mockFeedItems.filter((item) => item.type !== "video");
